//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 2003_CLBombChessBoard.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"CLBombChessBoard")]
    public partial class CLBombChessBoard : PacketBase
    {
        public CLBombChessBoard() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 2003; } }

        private readonly List<PBChessField> m_ModifiedChessField = new List<PBChessField>();
        [ProtoMember(1, Name = @"ModifiedChessField", DataFormat = DataFormat.Default)]
        public List<PBChessField> ModifiedChessField
        {
            get { return m_ModifiedChessField; }
        }
    }
}
