//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1006_CLChangeGear.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"CLChangeGear")]
    public partial class CLChangeGear : PacketBase
    {
        public CLChangeGear() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 1006; } }

        private int? m_PutOnHeroId;
        [ProtoMember(1, Name = @"PutOnHeroId", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int PutOnHeroId
        {
            get { return m_PutOnHeroId ?? default(int); }
            set { m_PutOnHeroId = value; }
        }
        public bool HasPutOnHeroId { get { return m_PutOnHeroId != null; } }
        private void ResetPutOnHeroId() { m_PutOnHeroId = null; }
        private bool ShouldSerializePutOnHeroId() { return HasPutOnHeroId; }

        private int? m_TakeOffHeroId;
        [ProtoMember(2, Name = @"TakeOffHeroId", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int TakeOffHeroId
        {
            get { return m_TakeOffHeroId ?? default(int); }
            set { m_TakeOffHeroId = value; }
        }
        public bool HasTakeOffHeroId { get { return m_TakeOffHeroId != null; } }
        private void ResetTakeOffHeroId() { m_TakeOffHeroId = null; }
        private bool ShouldSerializeTakeOffHeroId() { return HasTakeOffHeroId; }

        private int? m_PutOnGearId;
        [ProtoMember(3, Name = @"PutOnGearId", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int PutOnGearId
        {
            get { return m_PutOnGearId ?? default(int); }
            set { m_PutOnGearId = value; }
        }
        public bool HasPutOnGearId { get { return m_PutOnGearId != null; } }
        private void ResetPutOnGearId() { m_PutOnGearId = null; }
        private bool ShouldSerializePutOnGearId() { return HasPutOnGearId; }

        private int? m_TakeOffGearId;
        [ProtoMember(4, Name = @"TakeOffGearId", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int TakeOffGearId
        {
            get { return m_TakeOffGearId ?? default(int); }
            set { m_TakeOffGearId = value; }
        }
        public bool HasTakeOffGearId { get { return m_TakeOffGearId != null; } }
        private void ResetTakeOffGearId() { m_TakeOffGearId = null; }
        private bool ShouldSerializeTakeOffGearId() { return HasTakeOffGearId; }
    }
}
