//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1037_CLChangePortrait.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"CLChangePortrait")]
    public partial class CLChangePortrait : PacketBase
    {
        public CLChangePortrait() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 1037; } }

        private int m_NewPortraitType;
        [ProtoMember(1, Name = @"NewPortraitType", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int NewPortraitType
        {
            get { return m_NewPortraitType; }
            set { m_NewPortraitType = value; }
        }
    }
}
