//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1042_CLClaimAchievementReward.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"CLClaimAchievementReward")]
    public partial class CLClaimAchievementReward : PacketBase
    {
        public CLClaimAchievementReward() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 1042; } }

        private int m_AchievementId;
        [ProtoMember(1, Name = @"AchievementId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int AchievementId
        {
            get { return m_AchievementId; }
            set { m_AchievementId = value; }
        }
    }
}
