//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 2307_CLGetArenaEnemyInfo.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"CLGetArenaEnemyInfo")]
    public partial class CLGetArenaEnemyInfo : PacketBase
    {
        public CLGetArenaEnemyInfo() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 2307; } }

        private int m_EnemyPlayerId;
        [ProtoMember(1, Name = @"EnemyPlayerId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int EnemyPlayerId
        {
            get { return m_EnemyPlayerId; }
            set { m_EnemyPlayerId = value; }
        }
    }
}
