//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1030_CLGetHeroesInfo.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"CLGetHeroesInfo")]
    public partial class CLGetHeroesInfo : PacketBase
    {
        public CLGetHeroesInfo() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 1030; } }

        private int m_PlayerId;
        [ProtoMember(1, Name = @"PlayerId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int PlayerId
        {
            get { return m_PlayerId; }
            set { m_PlayerId = value; }
        }

        private readonly List<int> m_HeroTypes = new List<int>();
        [ProtoMember(2, Name = @"HeroTypes", DataFormat = DataFormat.TwosComplement)]
        public List<int> HeroTypes
        {
            get { return m_HeroTypes; }
        }
    }
}
