//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 2305_CLGetArenaLivenessReward.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"CLGetArenaLivenessReward")]
    public partial class CLGetArenaLivenessReward : PacketBase
    {
        public CLGetArenaLivenessReward() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 2305; } }

        private int m_RewardIndex;
        [ProtoMember(1, Name = @"RewardIndex", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int RewardIndex
        {
            get { return m_RewardIndex; }
            set { m_RewardIndex = value; }
        }
    }
}
