//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 2110_CLGetFoundryReward.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"CLGetFoundryReward")]
    public partial class CLGetFoundryReward : PacketBase
    {
        public CLGetFoundryReward() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 2110; } }

        private int m_Level;
        [ProtoMember(1, Name = @"Level", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int Level
        {
            get { return m_Level; }
            set { m_Level = value; }
        }
    }
}
