//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 2200_CLGetChanceInfo.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"CLGetChanceInfo")]
    public partial class CLGetChanceInfo : PacketBase
    {
        public CLGetChanceInfo() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 2200; } }

        private int m_ChanceType;
        [ProtoMember(1, Name = @"ChanceType", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int ChanceType
        {
            get { return m_ChanceType; }
            set { m_ChanceType = value; }
        }
    }
}
