//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1013_CLGearLevelUp.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"CLGearLevelUp")]
    public partial class CLGearLevelUp : PacketBase
    {
        public CLGearLevelUp() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 1013; } }

        private int m_GearId;
        [ProtoMember(1, Name = @"GearId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int GearId
        {
            get { return m_GearId; }
            set { m_GearId = value; }
        }

        private bool m_IsUpToMax;
        [ProtoMember(2, Name = @"IsUpToMax", IsRequired = true, DataFormat = DataFormat.Default)]
        public bool IsUpToMax
        {
            get { return m_IsUpToMax; }
            set { m_IsUpToMax = value; }
        }

        private int m_HeroType;
        [ProtoMember(3, Name = @"HeroType", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int HeroType
        {
            get { return m_HeroType; }
            set { m_HeroType = value; }
        }
    }
}
