//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1015_CLGearCompose.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"CLGearCompose")]
    public partial class CLGearCompose : PacketBase
    {
        public CLGearCompose() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 1015; } }

        private readonly List<int> m_GearId = new List<int>();
        [ProtoMember(1, Name = @"GearId", DataFormat = DataFormat.TwosComplement)]
        public List<int> GearId
        {
            get { return m_GearId; }
        }

        private int? m_ItemId;
        [ProtoMember(2, Name = @"ItemId", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int ItemId
        {
            get { return m_ItemId ?? default(int); }
            set { m_ItemId = value; }
        }
        public bool HasItemId { get { return m_ItemId != null; } }
        private void ResetItemId() { m_ItemId = null; }
        private bool ShouldSerializeItemId() { return HasItemId; }
    }
}
