//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 2302_CLGetArenaRankList.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"CLGetArenaRankList")]
    public partial class CLGetArenaRankList : PacketBase
    {
        public CLGetArenaRankList() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 2302; } }

        private int m_PageIndex;
        [ProtoMember(1, Name = @"PageIndex", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int PageIndex
        {
            get { return m_PageIndex; }
            set { m_PageIndex = value; }
        }
    }
}
