//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 2500_CLOperationActivity.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"CLOperationActivity")]
    public partial class CLOperationActivity : PacketBase
    {
        public CLOperationActivity() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 2500; } }

        private readonly List<PBKeyValuePair> m_Params = new List<PBKeyValuePair>();
        [ProtoMember(1, Name = @"Params", DataFormat = DataFormat.Default)]
        public List<PBKeyValuePair> Params
        {
            get { return m_Params; }
        }
    }
}
