//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 3110_CLReceiveEnergyFromFriend.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"CLReceiveEnergyFromFriend")]
    public partial class CLReceiveEnergyFromFriend : PacketBase
    {
        public CLReceiveEnergyFromFriend() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 3110; } }

        private int m_FriendPlayerId;
        [ProtoMember(1, Name = @"FriendPlayerId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int FriendPlayerId
        {
            get { return m_FriendPlayerId; }
            set { m_FriendPlayerId = value; }
        }
    }
}
