//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 2103_CLRespondToGearFoundryInvitation.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"CLRespondToGearFoundryInvitation")]
    public partial class CLRespondToGearFoundryInvitation : PacketBase
    {
        public CLRespondToGearFoundryInvitation() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 2103; } }

        private int m_TeamId;
        [ProtoMember(1, Name = @"TeamId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int TeamId
        {
            get { return m_TeamId; }
            set { m_TeamId = value; }
        }

        private int m_InviterPlayerId;
        [ProtoMember(2, Name = @"InviterPlayerId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int InviterPlayerId
        {
            get { return m_InviterPlayerId; }
            set { m_InviterPlayerId = value; }
        }

        private bool m_Accept;
        [ProtoMember(3, Name = @"Accept", IsRequired = true, DataFormat = DataFormat.Default)]
        public bool Accept
        {
            get { return m_Accept; }
            set { m_Accept = value; }
        }
    }
}
