//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 3106_CLSendFriendRequest.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"CLSendFriendRequest")]
    public partial class CLSendFriendRequest : PacketBase
    {
        public CLSendFriendRequest() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 3106; } }

        private int m_FriendCandidatePlayerId;
        [ProtoMember(1, Name = @"FriendCandidatePlayerId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int FriendCandidatePlayerId
        {
            get { return m_FriendCandidatePlayerId; }
            set { m_FriendCandidatePlayerId = value; }
        }
    }
}
