//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1033_CLSelectNearbyPlayers.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"CLSelectNearbyPlayers")]
    public partial class CLSelectNearbyPlayers : PacketBase
    {
        public CLSelectNearbyPlayers() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 1033; } }

        private readonly List<int> m_SelectedPlayers = new List<int>();
        [ProtoMember(1, Name = @"SelectedPlayers", DataFormat = DataFormat.TwosComplement)]
        public List<int> SelectedPlayers
        {
            get { return m_SelectedPlayers; }
        }
    }
}
