//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1029_CLSellGoods.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"CLSellGoods")]
    public partial class CLSellGoods : PacketBase
    {
        public CLSellGoods() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 1029; } }

        private readonly List<PBItemInfo> m_SoldItems = new List<PBItemInfo>();
        [ProtoMember(1, Name = @"SoldItems", DataFormat = DataFormat.Default)]
        public List<PBItemInfo> SoldItems
        {
            get { return m_SoldItems; }
        }

        private readonly List<PBGearInfo> m_SoldGears = new List<PBGearInfo>();
        [ProtoMember(2, Name = @"SoldGears", DataFormat = DataFormat.Default)]
        public List<PBGearInfo> SoldGears
        {
            get { return m_SoldGears; }
        }
    }
}
