//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1041_CLSkillUseExpItem.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"CLSkillUseExpItem")]
    public partial class CLSkillUseExpItem : PacketBase
    {
        public CLSkillUseExpItem() { }

        public override PacketType PacketType { get { return PacketType.ClientToLobbyServer; } }

        public override int PacketActionId { get { return 1041; } }

        private int m_HeroType;
        [ProtoMember(1, Name = @"HeroType", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int HeroType
        {
            get { return m_HeroType; }
            set { m_HeroType = value; }
        }

        private int m_SkillIndex;
        [ProtoMember(2, Name = @"SkillIndex", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int SkillIndex
        {
            get { return m_SkillIndex; }
            set { m_SkillIndex = value; }
        }

        private int m_ItemId;
        [ProtoMember(3, Name = @"ItemId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int ItemId
        {
            get { return m_ItemId; }
            set { m_ItemId = value; }
        }
    }
}
