//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 2003_LCBombChessBoard.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"LCBombChessBoard")]
    public partial class LCBombChessBoard : PacketBase
    {
        public LCBombChessBoard() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 2003; } }

        private bool m_Success;
        [ProtoMember(1, Name = @"Success", IsRequired = true, DataFormat = DataFormat.Default)]
        public bool Success
        {
            get { return m_Success; }
            set { m_Success = value; }
        }

        private int? m_RewardCoins;
        [ProtoMember(2, Name = @"RewardCoins", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int RewardCoins
        {
            get { return m_RewardCoins ?? default(int); }
            set { m_RewardCoins = value; }
        }
        public bool HasRewardCoins { get { return m_RewardCoins != null; } }
        private void ResetRewardCoins() { m_RewardCoins = null; }
        private bool ShouldSerializeRewardCoins() { return HasRewardCoins; }

        private int? m_RewardMoney;
        [ProtoMember(3, Name = @"RewardMoney", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int RewardMoney
        {
            get { return m_RewardMoney ?? default(int); }
            set { m_RewardMoney = value; }
        }
        public bool HasRewardMoney { get { return m_RewardMoney != null; } }
        private void ResetRewardMoney() { m_RewardMoney = null; }
        private bool ShouldSerializeRewardMoney() { return HasRewardMoney; }

        private int? m_RewardStarEnergy;
        [ProtoMember(4, Name = @"RewardStarEnergy", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int RewardStarEnergy
        {
            get { return m_RewardStarEnergy ?? default(int); }
            set { m_RewardStarEnergy = value; }
        }
        public bool HasRewardStarEnergy { get { return m_RewardStarEnergy != null; } }
        private void ResetRewardStarEnergy() { m_RewardStarEnergy = null; }
        private bool ShouldSerializeRewardStarEnergy() { return HasRewardStarEnergy; }

        private PBPlayerInfo m_PlayerInfo;
        [ProtoMember(5, Name = @"PlayerInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBPlayerInfo PlayerInfo
        {
            get { return m_PlayerInfo; }
            set { m_PlayerInfo = value; }
        }

        private PBReceivedItems m_ReceivedItems = null;
        [ProtoMember(6, Name = @"ReceivedItems", IsRequired = false, DataFormat = DataFormat.Default)]
        [System.ComponentModel.DefaultValue(null)]
        public PBReceivedItems ReceivedItems
        {
            get { return m_ReceivedItems; }
            set { m_ReceivedItems = value; }
        }
    }
}
