//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1006_LCChangeGear.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"LCChangeGear")]
    public partial class LCChangeGear : PacketBase
    {
        public LCChangeGear() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 1006; } }

        private int? m_PutOnGearId;
        [ProtoMember(1, Name = @"PutOnGearId", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int PutOnGearId
        {
            get { return m_PutOnGearId ?? default(int); }
            set { m_PutOnGearId = value; }
        }
        public bool HasPutOnGearId { get { return m_PutOnGearId != null; } }
        private void ResetPutOnGearId() { m_PutOnGearId = null; }
        private bool ShouldSerializePutOnGearId() { return HasPutOnGearId; }

        private int? m_TakeOffGearId;
        [ProtoMember(2, Name = @"TakeOffGearId", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int TakeOffGearId
        {
            get { return m_TakeOffGearId ?? default(int); }
            set { m_TakeOffGearId = value; }
        }
        public bool HasTakeOffGearId { get { return m_TakeOffGearId != null; } }
        private void ResetTakeOffGearId() { m_TakeOffGearId = null; }
        private bool ShouldSerializeTakeOffGearId() { return HasTakeOffGearId; }

        private PBLobbyHeroInfo m_TakeOffHeroInfo = null;
        [ProtoMember(3, Name = @"TakeOffHeroInfo", IsRequired = false, DataFormat = DataFormat.Default)]
        [System.ComponentModel.DefaultValue(null)]
        public PBLobbyHeroInfo TakeOffHeroInfo
        {
            get { return m_TakeOffHeroInfo; }
            set { m_TakeOffHeroInfo = value; }
        }

        private PBLobbyHeroInfo m_PutOnHeroInfo = null;
        [ProtoMember(4, Name = @"PutOnHeroInfo", IsRequired = false, DataFormat = DataFormat.Default)]
        [System.ComponentModel.DefaultValue(null)]
        public PBLobbyHeroInfo PutOnHeroInfo
        {
            get { return m_PutOnHeroInfo; }
            set { m_PutOnHeroInfo = value; }
        }
    }
}
