//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1016_LCChangeSoul.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"LCChangeSoul")]
    public partial class LCChangeSoul : PacketBase
    {
        public LCChangeSoul() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 1016; } }

        private int m_HeroId;
        [ProtoMember(1, Name = @"HeroId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int HeroId
        {
            get { return m_HeroId; }
            set { m_HeroId = value; }
        }

        private int? m_PutOnSoulId;
        [ProtoMember(2, Name = @"PutOnSoulId", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int PutOnSoulId
        {
            get { return m_PutOnSoulId ?? default(int); }
            set { m_PutOnSoulId = value; }
        }
        public bool HasPutOnSoulId { get { return m_PutOnSoulId != null; } }
        private void ResetPutOnSoulId() { m_PutOnSoulId = null; }
        private bool ShouldSerializePutOnSoulId() { return HasPutOnSoulId; }

        private int? m_TakeOffSoulId;
        [ProtoMember(3, Name = @"TakeOffSoulId", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int TakeOffSoulId
        {
            get { return m_TakeOffSoulId ?? default(int); }
            set { m_TakeOffSoulId = value; }
        }
        public bool HasTakeOffSoulId { get { return m_TakeOffSoulId != null; } }
        private void ResetTakeOffSoulId() { m_TakeOffSoulId = null; }
        private bool ShouldSerializeTakeOffSoulId() { return HasTakeOffSoulId; }

        private PBLobbyHeroInfo m_HeroInfo = null;
        [ProtoMember(4, Name = @"HeroInfo", IsRequired = false, DataFormat = DataFormat.Default)]
        [System.ComponentModel.DefaultValue(null)]
        public PBLobbyHeroInfo HeroInfo
        {
            get { return m_HeroInfo; }
            set { m_HeroInfo = value; }
        }
    }
}
