//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1042_LCClaimAchievementReward.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"LCClaimAchievementReward")]
    public partial class LCClaimAchievementReward : PacketBase
    {
        public LCClaimAchievementReward() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 1042; } }

        private int m_AchievementId;
        [ProtoMember(1, Name = @"AchievementId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int AchievementId
        {
            get { return m_AchievementId; }
            set { m_AchievementId = value; }
        }

        private PBTrackingAchievement m_NextTrackingAchievement = null;
        [ProtoMember(2, Name = @"NextTrackingAchievement", IsRequired = false, DataFormat = DataFormat.Default)]
        [System.ComponentModel.DefaultValue(null)]
        public PBTrackingAchievement NextTrackingAchievement
        {
            get { return m_NextTrackingAchievement; }
            set { m_NextTrackingAchievement = value; }
        }

        private PBPlayerInfo m_PlayerInfo = null;
        [ProtoMember(3, Name = @"PlayerInfo", IsRequired = false, DataFormat = DataFormat.Default)]
        [System.ComponentModel.DefaultValue(null)]
        public PBPlayerInfo PlayerInfo
        {
            get { return m_PlayerInfo; }
            set { m_PlayerInfo = value; }
        }

        private PBReceivedItems m_ReceivedItems = null;
        [ProtoMember(4, Name = @"ReceivedItems", IsRequired = false, DataFormat = DataFormat.Default)]
        [System.ComponentModel.DefaultValue(null)]
        public PBReceivedItems ReceivedItems
        {
            get { return m_ReceivedItems; }
            set { m_ReceivedItems = value; }
        }
    }
}
