//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1032_LCComposeHero.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"LCComposeHero")]
    public partial class LCComposeHero : PacketBase
    {
        public LCComposeHero() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 1032; } }

        private PBLobbyHeroInfo m_NewHero;
        [ProtoMember(1, Name = @"NewHero", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBLobbyHeroInfo NewHero
        {
            get { return m_NewHero; }
            set { m_NewHero = value; }
        }

        private PBItemInfo m_HeroPieceItem;
        [ProtoMember(2, Name = @"HeroPieceItem", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBItemInfo HeroPieceItem
        {
            get { return m_HeroPieceItem; }
            set { m_HeroPieceItem = value; }
        }
    }
}
