//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1026_LCCompleteStoryInstance.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"LCCompleteStoryInstance")]
    public partial class LCCompleteStoryInstance : PacketBase
    {
        public LCCompleteStoryInstance() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 1026; } }

        private int m_Count;
        [ProtoMember(1, Name = @"Count", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int Count
        {
            get { return m_Count; }
            set { m_Count = value; }
        }

        private PBReceivedItems m_ReceivedItems = null;
        [ProtoMember(2, Name = @"ReceivedItems", IsRequired = false, DataFormat = DataFormat.Default)]
        [System.ComponentModel.DefaultValue(null)]
        public PBReceivedItems ReceivedItems
        {
            get { return m_ReceivedItems; }
            set { m_ReceivedItems = value; }
        }

        private int m_StarLevel;
        [ProtoMember(3, Name = @"StarLevel", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int StarLevel
        {
            get { return m_StarLevel; }
            set { m_StarLevel = value; }
        }
    }
}
