//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 3104_LCDeleteFriend.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"LCDeleteFriend")]
    public partial class LCDeleteFriend : PacketBase
    {
        public LCDeleteFriend() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 3104; } }

        private int m_DeletedPlayerId;
        [ProtoMember(1, Name = @"DeletedPlayerId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int DeletedPlayerId
        {
            get { return m_DeletedPlayerId; }
            set { m_DeletedPlayerId = value; }
        }

        private bool m_IsActive;
        [ProtoMember(2, Name = @"IsActive", IsRequired = true, DataFormat = DataFormat.Default)]
        public bool IsActive
        {
            get { return m_IsActive; }
            set { m_IsActive = value; }
        }
    }
}
