//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 2401_LCEnterCosmosCrackInstance.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"LCEnterCosmosCrackInstance")]
    public partial class LCEnterCosmosCrackInstance : PacketBase
    {
        public LCEnterCosmosCrackInstance() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 2401; } }

        private int m_InstanceType;
        [ProtoMember(1, Name = @"InstanceType", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int InstanceType
        {
            get { return m_InstanceType; }
            set { m_InstanceType = value; }
        }

        private int m_NpcLevel;
        [ProtoMember(2, Name = @"NpcLevel", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int NpcLevel
        {
            get { return m_NpcLevel; }
            set { m_NpcLevel = value; }
        }
    }
}
