//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 2304_LCEndArenaBattle.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"LCEndArenaBattle")]
    public partial class LCEndArenaBattle : PacketBase
    {
        public LCEndArenaBattle() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 2304; } }

        private int m_MyRank;
        [ProtoMember(1, Name = @"MyRank", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int MyRank
        {
            get { return m_MyRank; }
            set { m_MyRank = value; }
        }

        private int m_ChallengeCount;
        [ProtoMember(2, Name = @"ChallengeCount", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int ChallengeCount
        {
            get { return m_ChallengeCount; }
            set { m_ChallengeCount = value; }
        }

        private PBArenaPlayerAndTeamInfo m_Enemy;
        [ProtoMember(3, Name = @"Enemy", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBArenaPlayerAndTeamInfo Enemy
        {
            get { return m_Enemy; }
            set { m_Enemy = value; }
        }

        private bool m_Win;
        [ProtoMember(4, Name = @"Win", IsRequired = true, DataFormat = DataFormat.Default)]
        public bool Win
        {
            get { return m_Win; }
            set { m_Win = value; }
        }

        private PBPlayerInfo m_Me;
        [ProtoMember(5, Name = @"Me", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBPlayerInfo Me
        {
            get { return m_Me; }
            set { m_Me = value; }
        }
    }
}
