//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1100_LCGetCommonShopInfo.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"LCGetCommonShopInfo")]
    public partial class LCGetCommonShopInfo : PacketBase
    {
        public LCGetCommonShopInfo() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 1100; } }

        private PBInt64 m_NextAutoRefreshTime;
        [ProtoMember(1, Name = @"NextAutoRefreshTime", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBInt64 NextAutoRefreshTime
        {
            get { return m_NextAutoRefreshTime; }
            set { m_NextAutoRefreshTime = value; }
        }

        private readonly List<PBShopItem> m_ShopItems = new List<PBShopItem>();
        [ProtoMember(2, Name = @"ShopItems", DataFormat = DataFormat.Default)]
        public List<PBShopItem> ShopItems
        {
            get { return m_ShopItems; }
        }
    }
}
