//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 2305_LCGetArenaLivenessReward.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"LCGetArenaLivenessReward")]
    public partial class LCGetArenaLivenessReward : PacketBase
    {
        public LCGetArenaLivenessReward() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 2305; } }

        private int m_RewardId;
        [ProtoMember(1, Name = @"RewardId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int RewardId
        {
            get { return m_RewardId; }
            set { m_RewardId = value; }
        }

        private readonly List<PBItemInfo> m_OpenedGoodInfo = new List<PBItemInfo>();
        [ProtoMember(2, Name = @"OpenedGoodInfo", DataFormat = DataFormat.Default)]
        public List<PBItemInfo> OpenedGoodInfo
        {
            get { return m_OpenedGoodInfo; }
        }

        private PBPlayerInfo m_PlayerInfo;
        [ProtoMember(3, Name = @"PlayerInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBPlayerInfo PlayerInfo
        {
            get { return m_PlayerInfo; }
            set { m_PlayerInfo = value; }
        }

        private PBReceivedItems m_ReceivedItems = null;
        [ProtoMember(4, Name = @"ReceivedItems", IsRequired = false, DataFormat = DataFormat.Default)]
        [System.ComponentModel.DefaultValue(null)]
        public PBReceivedItems ReceivedItems
        {
            get { return m_ReceivedItems; }
            set { m_ReceivedItems = value; }
        }
    }
}
