//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 2300_LCGetArenaInfo.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"LCGetArenaInfo")]
    public partial class LCGetArenaInfo : PacketBase
    {
        public LCGetArenaInfo() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 2300; } }

        private int m_MyRank;
        [ProtoMember(1, Name = @"MyRank", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int MyRank
        {
            get { return m_MyRank; }
            set { m_MyRank = value; }
        }

        private int m_ChallengeCount;
        [ProtoMember(2, Name = @"ChallengeCount", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int ChallengeCount
        {
            get { return m_ChallengeCount; }
            set { m_ChallengeCount = value; }
        }

        private int m_ArenaTokenCount;
        [ProtoMember(3, Name = @"ArenaTokenCount", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int ArenaTokenCount
        {
            get { return m_ArenaTokenCount; }
            set { m_ArenaTokenCount = value; }
        }

        private readonly List<PBArenaPlayerAndTeamInfo> m_Enemies = new List<PBArenaPlayerAndTeamInfo>();
        [ProtoMember(4, Name = @"Enemies", DataFormat = DataFormat.Default)]
        public List<PBArenaPlayerAndTeamInfo> Enemies
        {
            get { return m_Enemies; }
        }

        private int m_WinCount;
        [ProtoMember(5, Name = @"WinCount", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int WinCount
        {
            get { return m_WinCount; }
            set { m_WinCount = value; }
        }

        private readonly List<bool> m_ClaimedFlags = new List<bool>();
        [ProtoMember(6, Name = @"ClaimedFlags", DataFormat = DataFormat.Default)]
        public List<bool> ClaimedFlags
        {
            get { return m_ClaimedFlags; }
        }
    }
}
