//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 3100_LCGetNearbyPlayers.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"LCGetNearbyPlayers")]
    public partial class LCGetNearbyPlayers : PacketBase
    {
        public LCGetNearbyPlayers() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 3100; } }

        private readonly List<PBPlayerInfo> m_Players = new List<PBPlayerInfo>();
        [ProtoMember(1, Name = @"Players", DataFormat = DataFormat.Default)]
        public List<PBPlayerInfo> Players
        {
            get { return m_Players; }
        }

        private readonly List<PBLobbyHeroInfo> m_Heroes = new List<PBLobbyHeroInfo>();
        [ProtoMember(2, Name = @"Heroes", DataFormat = DataFormat.Default)]
        public List<PBLobbyHeroInfo> Heroes
        {
            get { return m_Heroes; }
        }

        private readonly List<bool> m_IsMyFriend = new List<bool>();
        [ProtoMember(3, Name = @"IsMyFriend", DataFormat = DataFormat.Default)]
        public List<bool> IsMyFriend
        {
            get { return m_IsMyFriend; }
        }
    }
}
