//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1036_LCGetActivitiesInfo.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"LCGetActivitiesInfo")]
    public partial class LCGetActivitiesInfo : PacketBase
    {
        public LCGetActivitiesInfo() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 1036; } }

        private readonly List<PBActivityInfo> m_ActivityInfo = new List<PBActivityInfo>();
        [ProtoMember(1, Name = @"ActivityInfo", DataFormat = DataFormat.Default)]
        public List<PBActivityInfo> ActivityInfo
        {
            get { return m_ActivityInfo; }
        }
    }
}
