//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1015_LCGearCompose.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"LCGearCompose")]
    public partial class LCGearCompose : PacketBase
    {
        public LCGearCompose() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 1015; } }

        private PBGearInfo m_NewGear = null;
        [ProtoMember(1, Name = @"NewGear", IsRequired = false, DataFormat = DataFormat.Default)]
        [System.ComponentModel.DefaultValue(null)]
        public PBGearInfo NewGear
        {
            get { return m_NewGear; }
            set { m_NewGear = value; }
        }

        private readonly List<int> m_RemovedGears = new List<int>();
        [ProtoMember(2, Name = @"RemovedGears", DataFormat = DataFormat.TwosComplement)]
        public List<int> RemovedGears
        {
            get { return m_RemovedGears; }
        }

        private PBPlayerInfo m_PlayerInfo;
        [ProtoMember(3, Name = @"PlayerInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBPlayerInfo PlayerInfo
        {
            get { return m_PlayerInfo; }
            set { m_PlayerInfo = value; }
        }

        private PBItemInfo m_ItemInfo = null;
        [ProtoMember(4, Name = @"ItemInfo", IsRequired = false, DataFormat = DataFormat.Default)]
        [System.ComponentModel.DefaultValue(null)]
        public PBItemInfo ItemInfo
        {
            get { return m_ItemInfo; }
            set { m_ItemInfo = value; }
        }
    }
}
