//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1302_LCGetSinglePvpInfo.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"LCGetSinglePvpInfo")]
    public partial class LCGetSinglePvpInfo : PacketBase
    {
        public LCGetSinglePvpInfo() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 1302; } }

        private int m_Rank;
        [ProtoMember(1, Name = @"Rank", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int Rank
        {
            get { return m_Rank; }
            set { m_Rank = value; }
        }

        private int m_Score;
        [ProtoMember(2, Name = @"Score", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int Score
        {
            get { return m_Score; }
            set { m_Score = value; }
        }

        private int m_ChallengeCount;
        [ProtoMember(3, Name = @"ChallengeCount", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int ChallengeCount
        {
            get { return m_ChallengeCount; }
            set { m_ChallengeCount = value; }
        }

        private int m_Season;
        [ProtoMember(4, Name = @"Season", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int Season
        {
            get { return m_Season; }
            set { m_Season = value; }
        }
    }
}
