//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1011_LCHeroElevationLevelUp.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"LCHeroElevationLevelUp")]
    public partial class LCHeroElevationLevelUp : PacketBase
    {
        public LCHeroElevationLevelUp() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 1011; } }

        private PBLobbyHeroInfo m_LobbyHeroInfo;
        [ProtoMember(1, Name = @"LobbyHeroInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBLobbyHeroInfo LobbyHeroInfo
        {
            get { return m_LobbyHeroInfo; }
            set { m_LobbyHeroInfo = value; }
        }

        private readonly List<int> m_RemovedGears = new List<int>();
        [ProtoMember(2, Name = @"RemovedGears", DataFormat = DataFormat.TwosComplement)]
        public List<int> RemovedGears
        {
            get { return m_RemovedGears; }
        }

        private PBItemInfo m_ItemInfo;
        [ProtoMember(3, Name = @"ItemInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBItemInfo ItemInfo
        {
            get { return m_ItemInfo; }
            set { m_ItemInfo = value; }
        }
    }
}
