//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 2402_LCLeaveCosmosCrackInstance.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"LCLeaveCosmosCrackInstance")]
    public partial class LCLeaveCosmosCrackInstance : PacketBase
    {
        public LCLeaveCosmosCrackInstance() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 2402; } }

        private int m_InstanceType;
        [ProtoMember(1, Name = @"InstanceType", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int InstanceType
        {
            get { return m_InstanceType; }
            set { m_InstanceType = value; }
        }

        private bool m_Win;
        [ProtoMember(2, Name = @"Win", IsRequired = true, DataFormat = DataFormat.Default)]
        public bool Win
        {
            get { return m_Win; }
            set { m_Win = value; }
        }

        private int m_RewardLevel;
        [ProtoMember(3, Name = @"RewardLevel", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int RewardLevel
        {
            get { return m_RewardLevel; }
            set { m_RewardLevel = value; }
        }

        private PBPlayerInfo m_PlayerInfo;
        [ProtoMember(4, Name = @"PlayerInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBPlayerInfo PlayerInfo
        {
            get { return m_PlayerInfo; }
            set { m_PlayerInfo = value; }
        }

        private PBReceivedItems m_ReceivedItems = null;
        [ProtoMember(5, Name = @"ReceivedItems", IsRequired = false, DataFormat = DataFormat.Default)]
        [System.ComponentModel.DefaultValue(null)]
        public PBReceivedItems ReceivedItems
        {
            get { return m_ReceivedItems; }
            set { m_ReceivedItems = value; }
        }
    }
}
