//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1000_LCLoginServer.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"LCLoginServer")]
    public partial class LCLoginServer : PacketBase
    {
        public LCLoginServer() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 1000; } }

        private bool m_Authorized;
        [ProtoMember(1, Name = @"Authorized", IsRequired = true, DataFormat = DataFormat.Default)]
        public bool Authorized
        {
            get { return m_Authorized; }
            set { m_Authorized = value; }
        }

        private bool m_NewAccount;
        [ProtoMember(2, Name = @"NewAccount", IsRequired = true, DataFormat = DataFormat.Default)]
        public bool NewAccount
        {
            get { return m_NewAccount; }
            set { m_NewAccount = value; }
        }
    }
}
