//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1101_LCManuallyRefreshCommonShop.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"LCManuallyRefreshCommonShop")]
    public partial class LCManuallyRefreshCommonShop : PacketBase
    {
        public LCManuallyRefreshCommonShop() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 1101; } }

        private PBPlayerInfo m_Me;
        [ProtoMember(1, Name = @"Me", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBPlayerInfo Me
        {
            get { return m_Me; }
            set { m_Me = value; }
        }

        private readonly List<PBShopItem> m_ShopItems = new List<PBShopItem>();
        [ProtoMember(2, Name = @"ShopItems", DataFormat = DataFormat.Default)]
        public List<PBShopItem> ShopItems
        {
            get { return m_ShopItems; }
        }
    }
}
