//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1039_LCOpenInInstanceChest.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"LCOpenInInstanceChest")]
    public partial class LCOpenInInstanceChest : PacketBase
    {
        public LCOpenInInstanceChest() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 1039; } }

        private readonly List<PBItemInfo> m_GoodsInfo = new List<PBItemInfo>();
        [ProtoMember(1, Name = @"GoodsInfo", DataFormat = DataFormat.Default)]
        public List<PBItemInfo> GoodsInfo
        {
            get { return m_GoodsInfo; }
        }

        private PBPlayerInfo m_PlayerInfo;
        [ProtoMember(2, Name = @"PlayerInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBPlayerInfo PlayerInfo
        {
            get { return m_PlayerInfo; }
            set { m_PlayerInfo = value; }
        }

        private PBReceivedItems m_ReceivedItems = null;
        [ProtoMember(5, Name = @"ReceivedItems", IsRequired = false, DataFormat = DataFormat.Default)]
        [System.ComponentModel.DefaultValue(null)]
        public PBReceivedItems ReceivedItems
        {
            get { return m_ReceivedItems; }
            set { m_ReceivedItems = value; }
        }
    }
}
