//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 2201_LCOpenChance.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"LCOpenChance")]
    public partial class LCOpenChance : PacketBase
    {
        public LCOpenChance() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 2201; } }

        private int m_ChanceType;
        [ProtoMember(1, Name = @"ChanceType", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int ChanceType
        {
            get { return m_ChanceType; }
            set { m_ChanceType = value; }
        }

        private int m_OpenedIndex;
        [ProtoMember(2, Name = @"OpenedIndex", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int OpenedIndex
        {
            get { return m_OpenedIndex; }
            set { m_OpenedIndex = value; }
        }

        private PBItemInfo m_OpenedGoodInfo;
        [ProtoMember(3, Name = @"OpenedGoodInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBItemInfo OpenedGoodInfo
        {
            get { return m_OpenedGoodInfo; }
            set { m_OpenedGoodInfo = value; }
        }

        private PBPlayerInfo m_PlayerInfo;
        [ProtoMember(4, Name = @"PlayerInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBPlayerInfo PlayerInfo
        {
            get { return m_PlayerInfo; }
            set { m_PlayerInfo = value; }
        }

        private PBLobbyHeroInfo m_LobbyHeroInfo = null;
        [ProtoMember(5, Name = @"LobbyHeroInfo", IsRequired = false, DataFormat = DataFormat.Default)]
        [System.ComponentModel.DefaultValue(null)]
        public PBLobbyHeroInfo LobbyHeroInfo
        {
            get { return m_LobbyHeroInfo; }
            set { m_LobbyHeroInfo = value; }
        }

        private PBReceivedItems m_ReceivedItems = null;
        [ProtoMember(6, Name = @"ReceivedItems", IsRequired = false, DataFormat = DataFormat.Default)]
        [System.ComponentModel.DefaultValue(null)]
        public PBReceivedItems ReceivedItems
        {
            get { return m_ReceivedItems; }
            set { m_ReceivedItems = value; }
        }

        private PBInt64 m_NextFreeTime = null;
        [ProtoMember(7, Name = @"NextFreeTime", IsRequired = false, DataFormat = DataFormat.Default)]
        [System.ComponentModel.DefaultValue(null)]
        public PBInt64 NextFreeTime
        {
            get { return m_NextFreeTime; }
            set { m_NextFreeTime = value; }
        }
    }
}
