//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 4004_LCPushAchievementProgress.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"LCPushAchievementProgress")]
    public partial class LCPushAchievementProgress : PacketBase
    {
        public LCPushAchievementProgress() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 4004; } }

        private readonly List<PBTrackingAchievement> m_TrackingAchievements = new List<PBTrackingAchievement>();
        [ProtoMember(1, Name = @"TrackingAchievements", DataFormat = DataFormat.Default)]
        public List<PBTrackingAchievement> TrackingAchievements
        {
            get { return m_TrackingAchievements; }
        }
    }
}
