//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 3107_LCReceiveFriendRequest.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"LCReceiveFriendRequest")]
    public partial class LCReceiveFriendRequest : PacketBase
    {
        public LCReceiveFriendRequest() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 3107; } }

        private PBPlayerInfo m_Player;
        [ProtoMember(1, Name = @"Player", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBPlayerInfo Player
        {
            get { return m_Player; }
            set { m_Player = value; }
        }
    }
}
