//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 2203_LCRefreshChanceInfo.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"LCRefreshChanceInfo")]
    public partial class LCRefreshChanceInfo : PacketBase
    {
        public LCRefreshChanceInfo() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 2203; } }

        private int m_ChanceType;
        [ProtoMember(1, Name = @"ChanceType", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int ChanceType
        {
            get { return m_ChanceType; }
            set { m_ChanceType = value; }
        }

        private readonly List<PBItemInfo> m_GoodInfo = new List<PBItemInfo>();
        [ProtoMember(2, Name = @"GoodInfo", DataFormat = DataFormat.Default)]
        public List<PBItemInfo> GoodInfo
        {
            get { return m_GoodInfo; }
        }

        private PBPlayerInfo m_PlayerInfo;
        [ProtoMember(3, Name = @"PlayerInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBPlayerInfo PlayerInfo
        {
            get { return m_PlayerInfo; }
            set { m_PlayerInfo = value; }
        }

        private int m_FreeChanceTimes;
        [ProtoMember(4, Name = @"FreeChanceTimes", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int FreeChanceTimes
        {
            get { return m_FreeChanceTimes; }
            set { m_FreeChanceTimes = value; }
        }
    }
}
