//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1027_LCResetStoryInstanceTimes.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"LCResetStoryInstanceTimes")]
    public partial class LCResetStoryInstanceTimes : PacketBase
    {
        public LCResetStoryInstanceTimes() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 1027; } }

        private int m_Count;
        [ProtoMember(1, Name = @"Count", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int Count
        {
            get { return m_Count; }
            set { m_Count = value; }
        }
    }
}
