//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 2301_LCRefreshArenaEnemies.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"LCRefreshArenaEnemies")]
    public partial class LCRefreshArenaEnemies : PacketBase
    {
        public LCRefreshArenaEnemies() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 2301; } }

        private readonly List<PBArenaPlayerAndTeamInfo> m_Enemies = new List<PBArenaPlayerAndTeamInfo>();
        [ProtoMember(1, Name = @"Enemies", DataFormat = DataFormat.Default)]
        public List<PBArenaPlayerAndTeamInfo> Enemies
        {
            get { return m_Enemies; }
        }
    }
}
