//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1041_LCSkillUseExpItem.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"LCSkillUseExpItem")]
    public partial class LCSkillUseExpItem : PacketBase
    {
        public LCSkillUseExpItem() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 1041; } }

        private PBLobbyHeroInfo m_HeroInfo;
        [ProtoMember(1, Name = @"HeroInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBLobbyHeroInfo HeroInfo
        {
            get { return m_HeroInfo; }
            set { m_HeroInfo = value; }
        }

        private PBItemInfo m_ItemInfo;
        [ProtoMember(2, Name = @"ItemInfo", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBItemInfo ItemInfo
        {
            get { return m_ItemInfo; }
            set { m_ItemInfo = value; }
        }
    }
}
