//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 1021_LCUnlockEpigraph.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"LCUnlockEpigraph")]
    public partial class LCUnlockEpigraph : PacketBase
    {
        public LCUnlockEpigraph() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToClient; } }

        public override int PacketActionId { get { return 1021; } }

        private readonly List<PBEpigraphInfo> m_Epigraphs = new List<PBEpigraphInfo>();
        [ProtoMember(1, Name = @"Epigraphs", DataFormat = DataFormat.Default)]
        public List<PBEpigraphInfo> Epigraphs
        {
            get { return m_Epigraphs; }
        }
    }
}
