//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 8004_LWPvpResult.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;
using ZyGames.Framework.Game.Contract;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"LWPvpResult")]
    public partial class LWPvpResult : PacketBase, IRemoteServerPacket
    {
        public LWPvpResult() { }

        public override PacketType PacketType { get { return PacketType.LobbyServerToWorldServer; } }

        public override int PacketActionId { get { return 8004; } }

        private int m_PlayerId;
        [ProtoMember(1, Name = @"PlayerId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int PlayerId
        {
            get { return m_PlayerId; }
            set { m_PlayerId = value; }
        }

        private int m_Score;
        [ProtoMember(2, Name = @"Score", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int Score
        {
            get { return m_Score; }
            set { m_Score = value; }
        }
    }
}
