//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: PBMeridianInfo.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"PBMeridianInfo")]
    public partial class PBMeridianInfo
    {
        public PBMeridianInfo() { }

        private int m_Id;
        [ProtoMember(1, Name = @"Id", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int Id
        {
            get { return m_Id; }
            set { m_Id = value; }
        }

        private readonly List<int> m_UnlockedStars = new List<int>();
        [ProtoMember(2, Name = @"UnlockedStars", DataFormat = DataFormat.TwosComplement)]
        public List<int> UnlockedStars
        {
            get { return m_UnlockedStars; }
        }
    }
}
