//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: PBReceivedItems.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"PBReceivedItems")]
    public partial class PBReceivedItems
    {
        public PBReceivedItems() { }

        private readonly List<PBItemInfo> m_ItemInfo = new List<PBItemInfo>();
        [ProtoMember(1, Name = @"ItemInfo", DataFormat = DataFormat.Default)]
        public List<PBItemInfo> ItemInfo
        {
            get { return m_ItemInfo; }
        }

        private readonly List<PBGearInfo> m_GearInfo = new List<PBGearInfo>();
        [ProtoMember(2, Name = @"GearInfo", DataFormat = DataFormat.Default)]
        public List<PBGearInfo> GearInfo
        {
            get { return m_GearInfo; }
        }

        private readonly List<PBSoulInfo> m_SoulInfo = new List<PBSoulInfo>();
        [ProtoMember(3, Name = @"SoulInfo", DataFormat = DataFormat.Default)]
        public List<PBSoulInfo> SoulInfo
        {
            get { return m_SoulInfo; }
        }

        private readonly List<PBEpigraphInfo> m_EpigraphInfo = new List<PBEpigraphInfo>();
        [ProtoMember(4, Name = @"EpigraphInfo", DataFormat = DataFormat.Default)]
        public List<PBEpigraphInfo> EpigraphInfo
        {
            get { return m_EpigraphInfo; }
        }
    }
}
