//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 8005_WLGetWorldSinglePvpRank.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;
using ZyGames.Framework.Game.Contract;

namespace Genesis.GameServer.LobbyServer
{
    [Serializable, ProtoContract(Name = @"WLGetWorldSinglePvpRank")]
    public partial class WLGetWorldSinglePvpRank : PacketBase, IRemoteServerPacket
    {
        public WLGetWorldSinglePvpRank() { }

        public override PacketType PacketType { get { return PacketType.WorldServerToLobbyServer; } }

        public override int PacketActionId { get { return 8005; } }

        private readonly List<PBPlayerInfo> m_PlayerInfo = new List<PBPlayerInfo>();
        [ProtoMember(1, Name = @"PlayerInfo", DataFormat = DataFormat.Default)]
        public List<PBPlayerInfo> PlayerInfo
        {
            get { return m_PlayerInfo; }
        }

        private readonly List<int> m_ServerId = new List<int>();
        [ProtoMember(2, Name = @"ServerId", DataFormat = DataFormat.TwosComplement)]
        public List<int> ServerId
        {
            get { return m_ServerId; }
        }

        private readonly List<int> m_Score = new List<int>();
        [ProtoMember(3, Name = @"Score", DataFormat = DataFormat.TwosComplement)]
        public List<int> Score
        {
            get { return m_Score; }
        }

        private int m_MyScore;
        [ProtoMember(4, Name = @"MyScore", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int MyScore
        {
            get { return m_MyScore; }
            set { m_MyScore = value; }
        }

        private int m_MyRank;
        [ProtoMember(5, Name = @"MyRank", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int MyRank
        {
            get { return m_MyRank; }
            set { m_MyRank = value; }
        }
    }
}
