//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 5103_CREntityImpact.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.RoomServer
{
    [Serializable, ProtoContract(Name = @"CREntityImpact")]
    public partial class CREntityImpact : PacketBase
    {
        public CREntityImpact() { }

        public override PacketType PacketType { get { return PacketType.ClientToRoomServer; } }

        public override int PacketActionId { get { return 5103; } }

        private int m_SerialId;
        [ProtoMember(1, Name = @"SerialId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int SerialId
        {
            get { return m_SerialId; }
            set { m_SerialId = value; }
        }

        private int? m_OriginEntityId;
        [ProtoMember(2, Name = @"OriginEntityId", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int OriginEntityId
        {
            get { return m_OriginEntityId ?? default(int); }
            set { m_OriginEntityId = value; }
        }
        public bool HasOriginEntityId { get { return m_OriginEntityId != null; } }
        private void ResetOriginEntityId() { m_OriginEntityId = null; }
        private bool ShouldSerializeOriginEntityId() { return HasOriginEntityId; }

        private PBTransformInfo m_OriginTransform = null;
        [ProtoMember(3, Name = @"OriginTransform", IsRequired = false, DataFormat = DataFormat.Default)]
        [System.ComponentModel.DefaultValue(null)]
        public PBTransformInfo OriginTransform
        {
            get { return m_OriginTransform; }
            set { m_OriginTransform = value; }
        }

        private int? m_OriginOwnerEntityId;
        [ProtoMember(4, Name = @"OriginOwnerEntityId", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int OriginOwnerEntityId
        {
            get { return m_OriginOwnerEntityId ?? default(int); }
            set { m_OriginOwnerEntityId = value; }
        }
        public bool HasOriginOwnerEntityId { get { return m_OriginOwnerEntityId != null; } }
        private void ResetOriginOwnerEntityId() { m_OriginOwnerEntityId = null; }
        private bool ShouldSerializeOriginOwnerEntityId() { return HasOriginOwnerEntityId; }

        private PBTransformInfo m_OriginOwnerTransform = null;
        [ProtoMember(5, Name = @"OriginOwnerTransform", IsRequired = false, DataFormat = DataFormat.Default)]
        [System.ComponentModel.DefaultValue(null)]
        public PBTransformInfo OriginOwnerTransform
        {
            get { return m_OriginOwnerTransform; }
            set { m_OriginOwnerTransform = value; }
        }

        private int? m_TargetEntityId;
        [ProtoMember(6, Name = @"TargetEntityId", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int TargetEntityId
        {
            get { return m_TargetEntityId ?? default(int); }
            set { m_TargetEntityId = value; }
        }
        public bool HasTargetEntityId { get { return m_TargetEntityId != null; } }
        private void ResetTargetEntityId() { m_TargetEntityId = null; }
        private bool ShouldSerializeTargetEntityId() { return HasTargetEntityId; }

        private PBTransformInfo m_TargetTransform = null;
        [ProtoMember(7, Name = @"TargetTransform", IsRequired = false, DataFormat = DataFormat.Default)]
        [System.ComponentModel.DefaultValue(null)]
        public PBTransformInfo TargetTransform
        {
            get { return m_TargetTransform; }
            set { m_TargetTransform = value; }
        }

        private int m_ImpactSourceType;
        [ProtoMember(8, Name = @"ImpactSourceType", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int ImpactSourceType
        {
            get { return m_ImpactSourceType; }
            set { m_ImpactSourceType = value; }
        }

        private int? m_SkillId;
        [ProtoMember(9, Name = @"SkillId", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int SkillId
        {
            get { return m_SkillId ?? default(int); }
            set { m_SkillId = value; }
        }
        public bool HasSkillId { get { return m_SkillId != null; } }
        private void ResetSkillId() { m_SkillId = null; }
        private bool ShouldSerializeSkillId() { return HasSkillId; }

        private int? m_BuffId;
        [ProtoMember(10, Name = @"BuffId", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int BuffId
        {
            get { return m_BuffId ?? default(int); }
            set { m_BuffId = value; }
        }
        public bool HasBuffId { get { return m_BuffId != null; } }
        private void ResetBuffId() { m_BuffId = null; }
        private bool ShouldSerializeBuffId() { return HasBuffId; }

        private int? m_AIId;
        [ProtoMember(11, Name = @"AIId", IsRequired = false, DataFormat = DataFormat.TwosComplement)]
        public int AIId
        {
            get { return m_AIId ?? default(int); }
            set { m_AIId = value; }
        }
        public bool HasAIId { get { return m_AIId != null; } }
        private void ResetAIId() { m_AIId = null; }
        private bool ShouldSerializeAIId() { return HasAIId; }

        private float? m_CurrentTime;
        [ProtoMember(12, Name = @"CurrentTime", IsRequired = false, DataFormat = DataFormat.FixedSize)]
        public float CurrentTime
        {
            get { return m_CurrentTime ?? default(float); }
            set { m_CurrentTime = value; }
        }
        public bool HasCurrentTime { get { return m_CurrentTime != null; } }
        private void ResetCurrentTime() { m_CurrentTime = null; }
        private bool ShouldSerializeCurrentTime() { return HasCurrentTime; }

        private readonly List<PBHPDamageImpact> m_HPDamageImpacts = new List<PBHPDamageImpact>();
        [ProtoMember(13, Name = @"HPDamageImpacts", DataFormat = DataFormat.Default)]
        public List<PBHPDamageImpact> HPDamageImpacts
        {
            get { return m_HPDamageImpacts; }
        }

        private readonly List<PBHPRecoverImpact> m_HPRecoverImpacts = new List<PBHPRecoverImpact>();
        [ProtoMember(14, Name = @"HPRecoverImpacts", DataFormat = DataFormat.Default)]
        public List<PBHPRecoverImpact> HPRecoverImpacts
        {
            get { return m_HPRecoverImpacts; }
        }

        private readonly List<PBSteadyDamageImpact> m_SteadyDamageImpacts = new List<PBSteadyDamageImpact>();
        [ProtoMember(15, Name = @"SteadyDamageImpacts", DataFormat = DataFormat.Default)]
        public List<PBSteadyDamageImpact> SteadyDamageImpacts
        {
            get { return m_SteadyDamageImpacts; }
        }

        private readonly List<PBStiffnessImpact> m_StiffnessImpacts = new List<PBStiffnessImpact>();
        [ProtoMember(16, Name = @"StiffnessImpacts", DataFormat = DataFormat.Default)]
        public List<PBStiffnessImpact> StiffnessImpacts
        {
            get { return m_StiffnessImpacts; }
        }

        private readonly List<PBFloatImpact> m_FloatImpacts = new List<PBFloatImpact>();
        [ProtoMember(17, Name = @"FloatImpacts", DataFormat = DataFormat.Default)]
        public List<PBFloatImpact> FloatImpacts
        {
            get { return m_FloatImpacts; }
        }

        private readonly List<PBBlownAwayImpact> m_BlownAwayImpacts = new List<PBBlownAwayImpact>();
        [ProtoMember(18, Name = @"BlownAwayImpacts", DataFormat = DataFormat.Default)]
        public List<PBBlownAwayImpact> BlownAwayImpacts
        {
            get { return m_BlownAwayImpacts; }
        }

        private readonly List<PBStunImpact> m_StunImpacts = new List<PBStunImpact>();
        [ProtoMember(19, Name = @"StunImpacts", DataFormat = DataFormat.Default)]
        public List<PBStunImpact> StunImpacts
        {
            get { return m_StunImpacts; }
        }

        private readonly List<PBFreezeImpact> m_FreezeImpacts = new List<PBFreezeImpact>();
        [ProtoMember(20, Name = @"FreezeImpacts", DataFormat = DataFormat.Default)]
        public List<PBFreezeImpact> FreezeImpacts
        {
            get { return m_FreezeImpacts; }
        }

        private readonly List<PBHardHitImpact> m_HardHitImpacts = new List<PBHardHitImpact>();
        [ProtoMember(21, Name = @"HardHitImpacts", DataFormat = DataFormat.Default)]
        public List<PBHardHitImpact> HardHitImpacts
        {
            get { return m_HardHitImpacts; }
        }

        private readonly List<PBSoundAndEffectImpact> m_SoundAndEffectImpacts = new List<PBSoundAndEffectImpact>();
        [ProtoMember(22, Name = @"SoundAndEffectImpacts", DataFormat = DataFormat.Default)]
        public List<PBSoundAndEffectImpact> SoundAndEffectImpacts
        {
            get { return m_SoundAndEffectImpacts; }
        }

        private readonly List<int> m_BuffIdsAddedToTarget = new List<int>();
        [ProtoMember(23, Name = @"BuffIdsAddedToTarget", DataFormat = DataFormat.TwosComplement)]
        public List<int> BuffIdsAddedToTarget
        {
            get { return m_BuffIdsAddedToTarget; }
        }
    }
}
