//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 5109_CREntityRemoveBuff.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.RoomServer
{
    [Serializable, ProtoContract(Name = @"CREntityRemoveBuff")]
    public partial class CREntityRemoveBuff : PacketBase
    {
        public CREntityRemoveBuff() { }

        public override PacketType PacketType { get { return PacketType.ClientToRoomServer; } }

        public override int PacketActionId { get { return 5109; } }

        private int m_SerialId;
        [ProtoMember(1, Name = @"SerialId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int SerialId
        {
            get { return m_SerialId; }
            set { m_SerialId = value; }
        }

        private int m_OriginEntityId;
        [ProtoMember(2, Name = @"OriginEntityId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int OriginEntityId
        {
            get { return m_OriginEntityId; }
            set { m_OriginEntityId = value; }
        }

        private PBTransformInfo m_OriginTransform;
        [ProtoMember(3, Name = @"OriginTransform", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBTransformInfo OriginTransform
        {
            get { return m_OriginTransform; }
            set { m_OriginTransform = value; }
        }

        private int m_TargetEntityId;
        [ProtoMember(4, Name = @"TargetEntityId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int TargetEntityId
        {
            get { return m_TargetEntityId; }
            set { m_TargetEntityId = value; }
        }

        private PBTransformInfo m_TargetTransform;
        [ProtoMember(5, Name = @"TargetTransform", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBTransformInfo TargetTransform
        {
            get { return m_TargetTransform; }
            set { m_TargetTransform = value; }
        }

        private readonly List<int> m_BuffTypeIds = new List<int>();
        [ProtoMember(6, Name = @"BuffTypeIds", DataFormat = DataFormat.TwosComplement)]
        public List<int> BuffTypeIds
        {
            get { return m_BuffTypeIds; }
        }
    }
}
