//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 5001_CRGetRoomInfo.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.RoomServer
{
    [Serializable, ProtoContract(Name = @"CRGetRoomInfo")]
    public partial class CRGetRoomInfo : PacketBase
    {
        public CRGetRoomInfo() { }

        public override PacketType PacketType { get { return PacketType.ClientToRoomServer; } }

        public override int PacketActionId { get { return 5001; } }

        private int m_PlayerId;
        [ProtoMember(1, Name = @"PlayerId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int PlayerId
        {
            get { return m_PlayerId; }
            set { m_PlayerId = value; }
        }

        private int m_RoomId;
        [ProtoMember(2, Name = @"RoomId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int RoomId
        {
            get { return m_RoomId; }
            set { m_RoomId = value; }
        }

        private string m_Token;
        [ProtoMember(3, Name = @"Token", IsRequired = true, DataFormat = DataFormat.Default)]
        public string Token
        {
            get { return m_Token; }
            set { m_Token = value; }
        }
    }
}
