//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: PBFreezeImpact.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.RoomServer
{
    [Serializable, ProtoContract(Name = @"PBFreezeImpact")]
    public partial class PBFreezeImpact
    {
        public PBFreezeImpact() { }

        private int m_ImpactId;
        [ProtoMember(1, Name = @"ImpactId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int ImpactId
        {
            get { return m_ImpactId; }
            set { m_ImpactId = value; }
        }

        private int m_StateCategory;
        [ProtoMember(2, Name = @"StateCategory", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int StateCategory
        {
            get { return m_StateCategory; }
            set { m_StateCategory = value; }
        }

        private float m_FreezeTime;
        [ProtoMember(3, Name = @"FreezeTime", IsRequired = true, DataFormat = DataFormat.FixedSize)]
        public float FreezeTime
        {
            get { return m_FreezeTime; }
            set { m_FreezeTime = value; }
        }

        private float m_DownTime;
        [ProtoMember(4, Name = @"DownTime", IsRequired = true, DataFormat = DataFormat.FixedSize)]
        public float DownTime
        {
            get { return m_DownTime; }
            set { m_DownTime = value; }
        }
    }
}
