//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: 7001_RWCreateNewRoom.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;
using ZyGames.Framework.Game.Contract;

namespace Genesis.GameServer.RoomServer
{
    [Serializable, ProtoContract(Name = @"RWCreateNewRoom")]
    public partial class RWCreateNewRoom : PacketBase, IRemoteServerPacket
    {
        public RWCreateNewRoom() { }

        public override PacketType PacketType { get { return PacketType.RoomServerToWorldServer; } }

        public override int PacketActionId { get { return 7001; } }

        private int m_RoomId;
        [ProtoMember(1, Name = @"RoomId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int RoomId
        {
            get { return m_RoomId; }
            set { m_RoomId = value; }
        }

        private int m_InstanceId;
        [ProtoMember(2, Name = @"InstanceId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int InstanceId
        {
            get { return m_InstanceId; }
            set { m_InstanceId = value; }
        }
    }
}
