//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'TakeAction' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using System;
using ZyGames.Framework.Common.Serialization;
using ZyGames.Framework.Game.Contract.Action;
using ZyGames.Framework.Game.Service;

namespace Genesis.GameServer.LobbyServer
{
    public class Action2103 : AuthorizeAction
    {
        private CLRespondToGearFoundryInvitation m_RequestPacket;
        private LCRespondToGearFoundryInvitation m_ResponsePacket;
        private int m_UserId;

        public Action2103(ActionGetter actionGetter)
            : base((short)2103, actionGetter)
        {
            m_RequestPacket = null;
            m_ResponsePacket = new LCRespondToGearFoundryInvitation();
            m_UserId = 0;
        }

        public override bool GetUrlElement()
        {
            m_UserId = actionGetter.GetSession().UserId;
            m_RequestPacket = ProtoBufUtils.Deserialize<CLRespondToGearFoundryInvitation>((byte[])actionGetter.GetMessage());
            return true;
        }

        public override bool TakeAction()
        {
            if (!m_RequestPacket.Accept)
            {
                m_ResponsePacket.Accept = false;
                m_ResponsePacket.InviterPlayerId = m_RequestPacket.InviterPlayerId;
                m_ResponsePacket.TeamId = m_RequestPacket.TeamId;
                return true;
            }
            PlayerFoundryLogic pf = new PlayerFoundryLogic();
            pf.SetUser(m_UserId);
            if (!pf.JoinRoom(m_RequestPacket.TeamId))
            {
                ErrorCode = (int)ErrorType.RequireNotMet;
                ErrorInfo = "Room is full";
                return false;
            }
            m_ResponsePacket.Accept = true;
            m_ResponsePacket.Data = pf.GetAllFoundryData();
            m_ResponsePacket.InviterPlayerId = m_RequestPacket.InviterPlayerId;
            m_ResponsePacket.TeamId = m_RequestPacket.TeamId;
            pf.PushRoomPlayerChangedNotify();
            return true;
        }

        public override void WriteResponse(BaseGameResponse response)
        {
            CustomActionDispatcher.ResponseOK(response, actionGetter, ProtoBufUtils.Serialize(m_ResponsePacket));
        }
    }
}
