//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'TakeAction' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using System;
using ZyGames.Framework.Common.Serialization;
using ZyGames.Framework.Game.Contract.Action;
using ZyGames.Framework.Game.Service;

namespace Genesis.GameServer.LobbyServer
{
    public class Action1103 : AuthorizeAction
    {
        private CLGetVipShopInfo m_RequestPacket;
        private LCGetVipShopInfo m_ResponsePacket;
        private int m_UserId;

        public Action1103(ActionGetter actionGetter)
            : base((short)1103, actionGetter)
        {
            m_RequestPacket = null;
            m_ResponsePacket = new LCGetVipShopInfo();
            m_UserId = 0;
        }

        public override bool GetUrlElement()
        {
            m_UserId = actionGetter.GetSession().UserId;
            m_RequestPacket = ProtoBufUtils.Deserialize<CLGetVipShopInfo>((byte[])actionGetter.GetMessage());
            return true;
        }

        public override bool TakeAction()
        {
            PlayerVipShopLogic pds = new PlayerVipShopLogic();
            pds.SetUser(m_UserId);
            var playerShopInfo = pds.GetShopInfo();
            m_ResponsePacket.NextAutoRefreshTime = playerShopInfo.NextRefreshTime;
            foreach (var shopItem in playerShopInfo.ShopItems)
            {
                m_ResponsePacket.ShopItems.Add(new PBShopItem()
                {
                    TypeId = shopItem.ItemType,
                    Count = shopItem.ItemCount,
                    Currency = shopItem.CurrencyType,
                    PurchasedTimes = shopItem.PurchasedTimes,
                    MaxPurchasedTimes = 1,
                    OriginalPrice = shopItem.OriginalPrice,
                    DiscountedPrice = shopItem.DiscountedPrice,
                });
            }
            return true;
        }

        public override void WriteResponse(BaseGameResponse response)
        {
            CustomActionDispatcher.ResponseOK(response, actionGetter, ProtoBufUtils.Serialize(m_ResponsePacket));
        }
    }
}
