//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'TakeAction' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using System;
using ZyGames.Framework.Common.Serialization;
using ZyGames.Framework.Game.Contract.Action;
using ZyGames.Framework.Game.Service;

namespace Genesis.GameServer.LobbyServer
{
    public class Action1301 : AuthorizeAction
    {
        private CLStopSinglePvpMatching m_RequestPacket;
        private LCStopSinglePvpMatching m_ResponsePacket;
        private int m_UserId;

        public Action1301(ActionGetter actionGetter)
            : base((short)1301, actionGetter)
        {
            m_RequestPacket = null;
            m_ResponsePacket = new LCStopSinglePvpMatching();
            m_UserId = 0;
        }

        public override bool GetUrlElement()
        {
            m_UserId = actionGetter.GetSession().UserId;
            m_RequestPacket = ProtoBufUtils.Deserialize<CLStopSinglePvpMatching>((byte[])actionGetter.GetMessage());
            return true;
        }

        public override bool TakeAction()
        {
            if (!PVPLogic.StopSingleMatch(m_UserId))
            {
                ErrorCode = (int)ErrorType.CannotStopMatching;
                ErrorInfo = "You have already matched";
                return false;
            }
            return true;
        }

        public override void WriteResponse(BaseGameResponse response)
        {
            CustomActionDispatcher.ResponseOK(response, actionGetter, ProtoBufUtils.Serialize(m_ResponsePacket));
        }
    }
}
