//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'TakeAction' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using System;
using ZyGames.Framework.Common.Serialization;
using ZyGames.Framework.Game.Contract.Action;
using ZyGames.Framework.Game.Service;

namespace Genesis.GameServer.LobbyServer
{
    public class Action1037 : AuthorizeAction
    {
        private CLChangePortrait m_RequestPacket;
        private LCChangePortrait m_ResponsePacket;
        private int m_UserId;

        public Action1037(ActionGetter actionGetter)
            : base((short)1037, actionGetter)
        {
            m_RequestPacket = null;
            m_ResponsePacket = new LCChangePortrait();
            m_UserId = 0;
        }

        public override bool GetUrlElement()
        {
            m_UserId = actionGetter.GetSession().UserId;
            m_RequestPacket = ProtoBufUtils.Deserialize<CLChangePortrait>((byte[])actionGetter.GetMessage());
            return true;
        }

        public override bool TakeAction()
        {
            PlayerLogic p = new PlayerLogic();
            p.SetUser(m_UserId);
            if(p.MyPlayer == null)
            {
                ErrorCode = (int)ErrorType.CannotOpenChance;
                ErrorInfo = "user data error";
                return false;
            }
            p.MyPlayer.PortraitType = m_RequestPacket.NewPortraitType;
            m_ResponsePacket.PlayerInfo = new PBPlayerInfo()
            {
                Id = m_UserId,
                PortraitType = p.MyPlayer.PortraitType
            };
            return true;
        }

        public override void WriteResponse(BaseGameResponse response)
        {
            CustomActionDispatcher.ResponseOK(response, actionGetter, ProtoBufUtils.Serialize(m_ResponsePacket));
        }
    }
}
