//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'TakeAction' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using System;
using ZyGames.Framework.Common.Serialization;
using ZyGames.Framework.Game.Contract.Action;
using ZyGames.Framework.Game.Service;

namespace Genesis.GameServer.LobbyServer
{
    public class Action2101 : AuthorizeAction
    {
        private CLCreateGearFoundryTeam m_RequestPacket;
        private LCCreateGearFoundryTeam m_ResponsePacket;
        private int m_UserId;

        public Action2101(ActionGetter actionGetter)
            : base((short)2101, actionGetter)
        {
            m_RequestPacket = null;
            m_ResponsePacket = new LCCreateGearFoundryTeam();
            m_UserId = 0;
        }

        public override bool GetUrlElement()
        {
            m_UserId = actionGetter.GetSession().UserId;
            m_RequestPacket = ProtoBufUtils.Deserialize<CLCreateGearFoundryTeam>((byte[])actionGetter.GetMessage());
            return true;
        }

        public override bool TakeAction()
        {
            PlayerFoundryLogic pf = new PlayerFoundryLogic();
            pf.SetUser(m_UserId);
            if (!pf.CreateRoom())
            {
                ErrorCode = (int)ErrorType.CanNotCreateRoom;
                ErrorInfo = "You must quit your room before you create a room";
                return false;
            }
            m_ResponsePacket.TeamId = pf.GetPlayerFoundryInfo().CurrentRoomId;
            return true;
        }

        public override void WriteResponse(BaseGameResponse response)
        {
            CustomActionDispatcher.ResponseOK(response, actionGetter, ProtoBufUtils.Serialize(m_ResponsePacket));
        }
    }
}
