//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'TakeAction' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using System;
using ZyGames.Framework.Common.Serialization;
using ZyGames.Framework.Game.Contract.Action;
using ZyGames.Framework.Game.Service;

namespace Genesis.GameServer.LobbyServer
{
    public class Action1009 : AuthorizeAction
    {
        private CLChangeHeroTeam m_RequestPacket;
        private LCChangeHeroTeam m_ResponsePacket;
        private int m_UserId;

        public Action1009(ActionGetter actionGetter)
            : base((short)1009, actionGetter)
        {
            m_UserId = 0;
            m_RequestPacket = null;
            m_ResponsePacket = new LCChangeHeroTeam();
        }

        public override bool GetUrlElement()
        {
            m_UserId = actionGetter.GetSession().UserId;
            m_RequestPacket = ProtoBufUtils.Deserialize<CLChangeHeroTeam>((byte[])actionGetter.GetMessage());
            return true;
        }

        public override bool TakeAction()
        {
            HeroTeamLogic team = new HeroTeamLogic();
            team.SetUser(actionGetter.GetSession().UserId);
            if (!team.AssignHero(m_RequestPacket.HeroTeamInfo.HeroType))
            {
                ErrorCode = (int)ErrorType.CannotOpenChance;
                ErrorInfo = "Wrong Hero Team Info";
                return false;
            }
            m_ResponsePacket.HeroTeamInfo = new PBHeroTeamInfo();
            m_ResponsePacket.HeroTeamInfo.HeroType.AddRange(team.MyHeroTeam.Team);
            return true;
        }

        public override void WriteResponse(BaseGameResponse response)
        {
            CustomActionDispatcher.ResponseOK(response, actionGetter, ProtoBufUtils.Serialize(m_ResponsePacket));
        }
    }
}
