//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'TakeAction' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using System;
using ZyGames.Framework.Common.Serialization;
using ZyGames.Framework.Game.Contract.Action;
using ZyGames.Framework.Game.Service;

namespace Genesis.GameServer.LobbyServer
{
    public class Action2301 : AuthorizeAction
    {
        private CLRefreshArenaEnemies m_RequestPacket;
        private LCRefreshArenaEnemies m_ResponsePacket;
        private int m_UserId;

        public Action2301(ActionGetter actionGetter)
            : base((short)2301, actionGetter)
        {
            m_RequestPacket = null;
            m_ResponsePacket = new LCRefreshArenaEnemies();
            m_UserId = 0;
        }

        public override bool GetUrlElement()
        {
            m_UserId = actionGetter.GetSession().UserId;
            m_RequestPacket = ProtoBufUtils.Deserialize<CLRefreshArenaEnemies>((byte[])actionGetter.GetMessage());
            return true;
        }

        public override bool TakeAction()
        {
            ArenaRankLogic ar = new ArenaRankLogic();
            var matchPlayers = ar.GetMatchPlayers(m_UserId);
            PlayerLogic p = new PlayerLogic();
            foreach(var player in matchPlayers)
            {
                PBArenaPlayerAndTeamInfo enemy = new PBArenaPlayerAndTeamInfo();
                enemy.Rank = player.RankId;
                p.SetUser(player.PlayerId);
                enemy.PlayerInfo = new PBPlayerInfo()
                {
                    Id = player.PlayerId,
                    Name = p.MyPlayer.Name,
                    Level = p.MyPlayer.Level,
                    PortraitType = p.MyPlayer.PortraitType
                };
                m_ResponsePacket.Enemies.Add(enemy);
            }
            return true;
        }

        public override void WriteResponse(BaseGameResponse response)
        {
            CustomActionDispatcher.ResponseOK(response, actionGetter, ProtoBufUtils.Serialize(m_ResponsePacket));
        }
    }
}
