//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'TakeAction' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using System;
using ZyGames.Framework.Common.Serialization;
using ZyGames.Framework.Game.Contract.Action;
using ZyGames.Framework.Game.Service;

namespace Genesis.GameServer.LobbyServer
{
    public class Action3102 : AuthorizeAction
    {
        private CLGetRecommendedPlayers m_RequestPacket;
        private LCGetRecommendedPlayers m_ResponsePacket;
        private int m_UserId;

        public Action3102(ActionGetter actionGetter)
            : base((short)3102, actionGetter)
        {
            m_RequestPacket = null;
            m_ResponsePacket = new LCGetRecommendedPlayers();
            m_UserId = 0;
        }

        public override bool GetUrlElement()
        {
            m_UserId = actionGetter.GetSession().UserId;
            m_RequestPacket = ProtoBufUtils.Deserialize<CLGetRecommendedPlayers>((byte[])actionGetter.GetMessage());
            return true;
        }

        public override bool TakeAction()
        {
            PlayerFriendsLogic pf = new PlayerFriendsLogic();
            pf.SetUser(m_UserId);
            foreach(var player in pf.GetRecommendedPlayers())
            {
                m_ResponsePacket.Players.Add(new PBPlayerInfo()
                {
                    Id = player.Id,
                    Name = player.Name,
                    Level = player.Level,
                    VipLevel = player.VIPLevel,
                    LastLoginInTicks = player.LastLoginTime,
                    IsOnline = player.Status == PlayerStatus.Online
                });
            }
            return true;
        }

        public override void WriteResponse(BaseGameResponse response)
        {
            CustomActionDispatcher.ResponseOK(response, actionGetter, ProtoBufUtils.Serialize(m_ResponsePacket));
        }
    }
}
