//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// You may need to modify 'TakeAction' method.
// Don't modify the rest unless you know what you're doing.
//----------------------------------------------------------------------------------------------------

using System;
using ZyGames.Framework.Common.Serialization;
using ZyGames.Framework.Game.Contract.Action;
using ZyGames.Framework.Game.Service;

namespace Genesis.GameServer.LobbyServer
{
    public class Action3110 : AuthorizeAction
    {
        private CLReceiveEnergyFromFriend m_RequestPacket;
        private LCReceiveEnergyFromFriend m_ResponsePacket;
        private int m_UserId;

        public Action3110(ActionGetter actionGetter)
            : base((short)3110, actionGetter)
        {
            m_RequestPacket = null;
            m_ResponsePacket = new LCReceiveEnergyFromFriend();
            m_UserId = 0;
        }

        public override bool GetUrlElement()
        {
            m_UserId = actionGetter.GetSession().UserId;
            m_RequestPacket = ProtoBufUtils.Deserialize<CLReceiveEnergyFromFriend>((byte[])actionGetter.GetMessage());
            return true;
        }

        public override bool TakeAction()
        {
            PlayerFriendsLogic pf = new PlayerFriendsLogic();
            pf.SetUser(m_UserId);
            if (!pf.ReceiveEnergy(m_RequestPacket.FriendPlayerId))
            {
                ErrorCode = (int)ErrorType.CannotOpenChance;
                ErrorInfo = "you can not receive energy from this player";
                return false;
            }
            m_ResponsePacket.FriendPlayerId = m_RequestPacket.FriendPlayerId;
            PlayerLogic player = new PlayerLogic();
            player.SetUser(m_UserId);
            long nextRecoverTime;
            player.AddEnergy(1, out nextRecoverTime);
            m_ResponsePacket.Me = new PBPlayerInfo()
            {
                Id = player.MyPlayer.Id,
                Energy = player.MyPlayer.Energy,
                NextEnergyRecoveryTime = nextRecoverTime
            };
            m_ResponsePacket.RemainCount = GameConsts.Social.MaxReceiveCount - pf.MyFriends.ReceiveCount;
            return true;
        }

        public override void WriteResponse(BaseGameResponse response)
        {
            CustomActionDispatcher.ResponseOK(response, actionGetter, ProtoBufUtils.Serialize(m_ResponsePacket));
        }
    }
}
