# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: 101_CLServerCommand.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='101_CLServerCommand.proto',
  package='',
  serialized_pb='\n\x19\x31\x30\x31_CLServerCommand.proto\"=\n\x0f\x43LServerCommand\x12\x0c\n\x04Type\x18\x01 \x02(\x05\x12\x0e\n\x06Params\x18\x02 \x01(\t\x12\x0c\n\x04test\x18\x03 \x01(\x05')




_CLSERVERCOMMAND = _descriptor.Descriptor(
  name='CLServerCommand',
  full_name='CLServerCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Type', full_name='CLServerCommand.Type', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Params', full_name='CLServerCommand.Params', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='test', full_name='CLServerCommand.test', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=29,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['CLServerCommand'] = _CLSERVERCOMMAND

class CLServerCommand(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CLSERVERCOMMAND

  # @@protoc_insertion_point(class_scope:CLServerCommand)


# @@protoc_insertion_point(module_scope)
