# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Gears.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Gears.proto',
  package='',
  serialized_pb='\n\x0bGears.proto\"C\n\x05Gears\x12\n\n\x02Id\x18\x01 \x02(\x05\x12\x0e\n\x06TypeId\x18\x02 \x02(\x05\x12\r\n\x05Level\x18\x03 \x02(\x05\x12\x0f\n\x07Removed\x18\x04 \x02(\x08')




_GEARS = _descriptor.Descriptor(
  name='Gears',
  full_name='Gears',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='Gears.Id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TypeId', full_name='Gears.TypeId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Level', full_name='Gears.Level', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Removed', full_name='Gears.Removed', index=3,
      number=4, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=15,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['Gears'] = _GEARS

class Gears(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GEARS

  # @@protoc_insertion_point(class_scope:Gears)


# @@protoc_insertion_point(module_scope)
