# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HeroTeam.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='HeroTeam.proto',
  package='',
  serialized_pb='\n\x0eHeroTeam.proto\"*\n\x08HeroTeam\x12\x10\n\x08PlayerId\x18\x01 \x02(\x05\x12\x0c\n\x04Team\x18\x02 \x02(\t')




_HEROTEAM = _descriptor.Descriptor(
  name='HeroTeam',
  full_name='HeroTeam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='PlayerId', full_name='HeroTeam.PlayerId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Team', full_name='HeroTeam.Team', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=18,
  serialized_end=60,
)

DESCRIPTOR.message_types_by_name['HeroTeam'] = _HEROTEAM

class HeroTeam(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HEROTEAM

  # @@protoc_insertion_point(class_scope:HeroTeam)


# @@protoc_insertion_point(module_scope)
