# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerChess.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PlayerChess.proto',
  package='',
  serialized_pb='\n\x11PlayerChess.proto\"\x82\x02\n\x0bPlayerChess\x12\x0e\n\x06UserId\x18\x01 \x02(\x05\x12\r\n\x05\x43ount\x18\x02 \x02(\x05\x12\r\n\x05Token\x18\x03 \x02(\x05\x12\r\n\x05\x41nger\x18\x04 \x02(\x05\x12\n\n\x02HP\x18\x05 \x02(\t\x12\x12\n\nChessBoard\x18\x06 \x02(\t\x12\x0f\n\x07GotCoin\x18\x07 \x02(\x05\x12\x10\n\x08GotMoney\x18\x08 \x02(\x05\x12\x15\n\rGotStarEnergy\x18\t \x02(\x05\x12\x10\n\x08GotGears\x18\n \x02(\t\x12\x10\n\x08GotItems\x18\x0b \x02(\t\x12\x15\n\rLastResetTime\x18\x0c \x02(\t\x12\x0e\n\x06MyTeam\x18\r \x02(\t\x12\x11\n\tOpenCount\x18\x0e \x02(\x05')




_PLAYERCHESS = _descriptor.Descriptor(
  name='PlayerChess',
  full_name='PlayerChess',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='UserId', full_name='PlayerChess.UserId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Count', full_name='PlayerChess.Count', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Token', full_name='PlayerChess.Token', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Anger', full_name='PlayerChess.Anger', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='HP', full_name='PlayerChess.HP', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ChessBoard', full_name='PlayerChess.ChessBoard', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GotCoin', full_name='PlayerChess.GotCoin', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GotMoney', full_name='PlayerChess.GotMoney', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GotStarEnergy', full_name='PlayerChess.GotStarEnergy', index=8,
      number=9, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GotGears', full_name='PlayerChess.GotGears', index=9,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GotItems', full_name='PlayerChess.GotItems', index=10,
      number=11, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LastResetTime', full_name='PlayerChess.LastResetTime', index=11,
      number=12, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MyTeam', full_name='PlayerChess.MyTeam', index=12,
      number=13, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='OpenCount', full_name='PlayerChess.OpenCount', index=13,
      number=14, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=280,
)

DESCRIPTOR.message_types_by_name['PlayerChess'] = _PLAYERCHESS

class PlayerChess(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PLAYERCHESS

  # @@protoc_insertion_point(class_scope:PlayerChess)


# @@protoc_insertion_point(module_scope)
