# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerInstanceDrop.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PlayerInstanceDrop.proto',
  package='',
  serialized_pb='\n\x18PlayerInstanceDrop.proto\"J\n\x12PlayerInstanceDrop\x12\x0e\n\x06UserId\x18\x01 \x02(\x05\x12\x12\n\nInstanceId\x18\x02 \x02(\x05\x12\x10\n\x08\x44ropList\x18\x03 \x02(\t')




_PLAYERINSTANCEDROP = _descriptor.Descriptor(
  name='PlayerInstanceDrop',
  full_name='PlayerInstanceDrop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='UserId', full_name='PlayerInstanceDrop.UserId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='InstanceId', full_name='PlayerInstanceDrop.InstanceId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DropList', full_name='PlayerInstanceDrop.DropList', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=28,
  serialized_end=102,
)

DESCRIPTOR.message_types_by_name['PlayerInstanceDrop'] = _PLAYERINSTANCEDROP

class PlayerInstanceDrop(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PLAYERINSTANCEDROP

  # @@protoc_insertion_point(class_scope:PlayerInstanceDrop)


# @@protoc_insertion_point(module_scope)
