# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerPackage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PlayerPackage.proto',
  package='',
  serialized_pb='\n\x13PlayerPackage.proto\"R\n\rPlayerPackage\x12\x0e\n\x06UserId\x18\x01 \x02(\x05\x12\x13\n\x0bInventories\x18\x02 \x02(\t\x12\r\n\x05Gears\x18\x03 \x02(\t\x12\r\n\x05Souls\x18\x04 \x02(\t')




_PLAYERPACKAGE = _descriptor.Descriptor(
  name='PlayerPackage',
  full_name='PlayerPackage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='UserId', full_name='PlayerPackage.UserId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Inventories', full_name='PlayerPackage.Inventories', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Gears', full_name='PlayerPackage.Gears', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Souls', full_name='PlayerPackage.Souls', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=23,
  serialized_end=105,
)

DESCRIPTOR.message_types_by_name['PlayerPackage'] = _PLAYERPACKAGE

class PlayerPackage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PLAYERPACKAGE

  # @@protoc_insertion_point(class_scope:PlayerPackage)


# @@protoc_insertion_point(module_scope)
