# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerMeridian.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PlayerMeridian.proto',
  package='',
  serialized_pb='\n\x14PlayerMeridian.proto\";\n\x0ePlayerMeridian\x12\x0e\n\x06UserId\x18\x01 \x02(\x05\x12\x19\n\x11UnlockedMeridians\x18\x02 \x02(\t')




_PLAYERMERIDIAN = _descriptor.Descriptor(
  name='PlayerMeridian',
  full_name='PlayerMeridian',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='UserId', full_name='PlayerMeridian.UserId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='UnlockedMeridians', full_name='PlayerMeridian.UnlockedMeridians', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=24,
  serialized_end=83,
)

DESCRIPTOR.message_types_by_name['PlayerMeridian'] = _PLAYERMERIDIAN

class PlayerMeridian(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PLAYERMERIDIAN

  # @@protoc_insertion_point(class_scope:PlayerMeridian)


# @@protoc_insertion_point(module_scope)
