//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: PBBlownAwayImpact.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.WorldServer
{
    [Serializable, ProtoContract(Name = @"PBBlownAwayImpact")]
    public partial class PBBlownAwayImpact
    {
        public PBBlownAwayImpact() { }

        private int m_ImpactId;
        [ProtoMember(1, Name = @"ImpactId", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int ImpactId
        {
            get { return m_ImpactId; }
            set { m_ImpactId = value; }
        }

        private int m_StateCategory;
        [ProtoMember(2, Name = @"StateCategory", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int StateCategory
        {
            get { return m_StateCategory; }
            set { m_StateCategory = value; }
        }

        private int m_RaiseAnimationType;
        [ProtoMember(3, Name = @"RaiseAnimationType", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int RaiseAnimationType
        {
            get { return m_RaiseAnimationType; }
            set { m_RaiseAnimationType = value; }
        }

        private int m_FallingAnimationType;
        [ProtoMember(4, Name = @"FallingAnimationType", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int FallingAnimationType
        {
            get { return m_FallingAnimationType; }
            set { m_FallingAnimationType = value; }
        }

        private PBVector3 m_FloatVelocity;
        [ProtoMember(5, Name = @"FloatVelocity", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBVector3 FloatVelocity
        {
            get { return m_FloatVelocity; }
            set { m_FloatVelocity = value; }
        }

        private PBVector3 m_FloatFallingVelocity;
        [ProtoMember(6, Name = @"FloatFallingVelocity", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBVector3 FloatFallingVelocity
        {
            get { return m_FloatFallingVelocity; }
            set { m_FloatFallingVelocity = value; }
        }

        private float m_FloatTime;
        [ProtoMember(7, Name = @"FloatTime", IsRequired = true, DataFormat = DataFormat.FixedSize)]
        public float FloatTime
        {
            get { return m_FloatTime; }
            set { m_FloatTime = value; }
        }

        private float m_FloatFallingTime;
        [ProtoMember(8, Name = @"FloatFallingTime", IsRequired = true, DataFormat = DataFormat.FixedSize)]
        public float FloatFallingTime
        {
            get { return m_FloatFallingTime; }
            set { m_FloatFallingTime = value; }
        }

        private float m_DownTime;
        [ProtoMember(9, Name = @"DownTime", IsRequired = true, DataFormat = DataFormat.FixedSize)]
        public float DownTime
        {
            get { return m_DownTime; }
            set { m_DownTime = value; }
        }

        private float m_RepulseStartTime;
        [ProtoMember(10, Name = @"RepulseStartTime", IsRequired = true, DataFormat = DataFormat.FixedSize)]
        public float RepulseStartTime
        {
            get { return m_RepulseStartTime; }
            set { m_RepulseStartTime = value; }
        }

        private PBVector3 m_RepulseVelocity;
        [ProtoMember(11, Name = @"RepulseVelocity", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBVector3 RepulseVelocity
        {
            get { return m_RepulseVelocity; }
            set { m_RepulseVelocity = value; }
        }

        private float m_RepulseTime;
        [ProtoMember(12, Name = @"RepulseTime", IsRequired = true, DataFormat = DataFormat.FixedSize)]
        public float RepulseTime
        {
            get { return m_RepulseTime; }
            set { m_RepulseTime = value; }
        }

        private PBVector3 m_RepulseDirection;
        [ProtoMember(13, Name = @"RepulseDirection", IsRequired = true, DataFormat = DataFormat.Default)]
        public PBVector3 RepulseDirection
        {
            get { return m_RepulseDirection; }
            set { m_RepulseDirection = value; }
        }
    }
}
