//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: PBHeroTeamInfo.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.WorldServer
{
    [Serializable, ProtoContract(Name = @"PBHeroTeamInfo")]
    public partial class PBHeroTeamInfo
    {
        public PBHeroTeamInfo() { }

        private readonly List<int> m_HeroType = new List<int>();
        [ProtoMember(1, Name = @"HeroType", DataFormat = DataFormat.TwosComplement)]
        public List<int> HeroType
        {
            get { return m_HeroType; }
        }
    }
}
