//----------------------------------------------------------------------------------------------------
// This code was auto generated by tools.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// Proto source: PBInstance.proto
//----------------------------------------------------------------------------------------------------

using Genesis.GameServer.CommonLibrary;
using ProtoBuf;
using System;
using System.Collections.Generic;

namespace Genesis.GameServer.WorldServer
{
    [Serializable, ProtoContract(Name = @"PBInstance")]
    public partial class PBInstance
    {
        public PBInstance() { }

        private int m_Id;
        [ProtoMember(1, Name = @"Id", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int Id
        {
            get { return m_Id; }
            set { m_Id = value; }
        }

        private int m_StarCount;
        [ProtoMember(2, Name = @"StarCount", IsRequired = true, DataFormat = DataFormat.TwosComplement)]
        public int StarCount
        {
            get { return m_StarCount; }
            set { m_StarCount = value; }
        }
    }
}
